"""Primitive types for PlantUML diagrams.

All types are frozen dataclasses - immutable data with no behavior.
"""

from .common import (
    Color,
    ColorLike,
    DiagramArrowStyle,
    DiagramArrowStyleLike,
    Direction,
    ElementStyle,
    ElementStyleLike,
    FontStyle,
    Gradient,
    Label,
    LabelLike,
    LinePattern,
    LineStyle,
    LineStyleLike,
    Note,
    NotePosition,
    RegionSeparator,
    Spot,
    StateDiagramStyle,
    StateDiagramStyleLike,
    Stereotype,
    Style,
    StyleLike,
)
from .state import (
    CompositeState,
    ConcurrentState,
    PseudoState,
    PseudoStateKind,
    Region,
    StateDiagram,
    StateDiagramElement,
    StateNode,
    Transition,
)

__all__ = [
    # Common
    "Color",
    "ColorLike",
    "DiagramArrowStyle",
    "DiagramArrowStyleLike",
    "Direction",
    "ElementStyle",
    "ElementStyleLike",
    "FontStyle",
    "Gradient",
    "Label",
    "LabelLike",
    "LinePattern",
    "LineStyle",
    "LineStyleLike",
    "Note",
    "NotePosition",
    "RegionSeparator",
    "Spot",
    "StateDiagramStyle",
    "StateDiagramStyleLike",
    "Stereotype",
    "Style",
    "StyleLike",
    # State
    "CompositeState",
    "ConcurrentState",
    "PseudoState",
    "PseudoStateKind",
    "Region",
    "StateDiagram",
    "StateDiagramElement",
    "StateNode",
    "Transition",
]
