"""Primitive types for PlantUML diagrams.

All types are frozen dataclasses - immutable data with no behavior.
"""

from .common import (
    ActivityDiagramStyle,
    ActivityDiagramStyleLike,
    ClassDiagramStyle,
    ClassDiagramStyleLike,
    Color,
    ColorLike,
    DiagramArrowStyle,
    DiagramArrowStyleLike,
    Direction,
    ElementStyle,
    ElementStyleLike,
    ExternalTheme,
    FontStyle,
    Gradient,
    JsonDiagramStyle,
    JsonDiagramStyleLike,
    Label,
    MindMapDiagramStyle,
    MindMapDiagramStyleLike,
    LabelLike,
    LayoutDirection,
    LayoutEngine,
    LinePattern,
    LineStyle,
    LineStyleLike,
    LineType,
    Note,
    NotePosition,
    ObjectDiagramStyle,
    ObjectDiagramStyleLike,
    PlantUMLBuiltinTheme,
    RegionSeparator,
    SequenceDiagramStyle,
    SequenceDiagramStyleLike,
    Spot,
    StateDiagramStyle,
    StateDiagramStyleLike,
    Stereotype,
    Style,
    StyleLike,
    ThemeLike,
    YamlDiagramStyle,
    YamlDiagramStyleLike,
)
from .activity import (
    Action,
    ActionShape,
    ActivityDiagram,
    ActivityElement,
    ActivityNote,
    Arrow,
    ArrowStyle,
    Break,
    Case,
    Connector,
    Detach,
    ElseIfBranch,
    End,
    Fork,
    Goto,
    Group,
    If,
    Kill,
    Partition,
    Repeat,
    Split,
    Start,
    Stop,
    Swimlane,
    Switch,
    While,
)
from .class_ import (
    ClassDiagram,
    ClassDiagramElement,
    ClassNode,
    ClassNote,
    ClassType,
    HideShow,
    Member,
    MemberModifier,
    Package,
    PackageStyle,
    Relationship,
    RelationType,
    Separator,
    SeparatorStyle,
    Together,
    Visibility,
)
from .sequence import (
    Activation,
    ActivationAction,
    Autonumber,
    Box,
    Delay,
    Divider,
    ElseBlock,
    GroupBlock,
    GroupType,
    Message,
    MessageArrowHead,
    MessageLineStyle,
    Participant,
    ParticipantType,
    Reference,
    Return,
    SequenceDiagram,
    SequenceDiagramElement,
    SequenceNote,
    Space,
)
from .component import (
    Component,
    ComponentDiagram,
    ComponentElement,
    ComponentNote,
    ComponentStyle,
    ComponentType,
    Container,
    ContainerType,
    Interface,
    Port,
)
from .component import Relationship as ComponentRelationship
from .component import RelationType as ComponentRelationType
from .deployment import (
    DeploymentDiagram,
    DeploymentDiagramElement,
    DeploymentElement,
    DeploymentNote,
)
from .deployment import ElementType as DeploymentElementType
from .deployment import Relationship as DeploymentRelationship
from .deployment import RelationType as DeploymentRelationType
from .usecase import (
    Actor,
    ActorStyle,
    UseCase,
    UseCaseDiagram,
    UseCaseDiagramElement,
    UseCaseNote,
)
from .usecase import Container as UseCaseContainer
from .usecase import ContainerType as UseCaseContainerType
from .usecase import Relationship as UseCaseRelationship
from .usecase import RelationType as UseCaseRelationType
from .object_ import (
    Field,
    Map,
    MapEntry,
    Object,
    ObjectDiagram,
    ObjectDiagramElement,
    ObjectNote,
)
from .object_ import Relationship as ObjectRelationship
from .object_ import RelationType as ObjectRelationType
from .state import (
    CompositeState,
    ConcurrentState,
    PseudoState,
    PseudoStateKind,
    Region,
    StateDiagram,
    StateDiagramElement,
    StateNode,
    Transition,
)
from .json_ import (
    JsonDiagram,
    YamlDiagram,
)
from .mindmap import (
    MindMapDiagram,
    MindMapNode,
)

__all__ = [
    # Common
    "ActivityDiagramStyle",
    "ActivityDiagramStyleLike",
    "ClassDiagramStyle",
    "ClassDiagramStyleLike",
    "Color",
    "ColorLike",
    "DiagramArrowStyle",
    "DiagramArrowStyleLike",
    "Direction",
    "ElementStyle",
    "ElementStyleLike",
    "ExternalTheme",
    "FontStyle",
    "Gradient",
    "JsonDiagramStyle",
    "JsonDiagramStyleLike",
    "Label",
    "LabelLike",
    "LayoutDirection",
    "LayoutEngine",
    "LinePattern",
    "LineStyle",
    "LineStyleLike",
    "LineType",
    "Note",
    "NotePosition",
    "ObjectDiagramStyle",
    "ObjectDiagramStyleLike",
    "PlantUMLBuiltinTheme",
    "RegionSeparator",
    "SequenceDiagramStyle",
    "SequenceDiagramStyleLike",
    "Spot",
    "StateDiagramStyle",
    "StateDiagramStyleLike",
    "Stereotype",
    "Style",
    "StyleLike",
    "ThemeLike",
    "YamlDiagramStyle",
    "YamlDiagramStyleLike",
    # Activity
    "Action",
    "ActionShape",
    "ActivityDiagram",
    "ActivityElement",
    "ActivityNote",
    "Arrow",
    "ArrowStyle",
    "Break",
    "Case",
    "Connector",
    "Detach",
    "ElseIfBranch",
    "End",
    "Fork",
    "Goto",
    "Group",
    "If",
    "Kill",
    "Partition",
    "Repeat",
    "Split",
    "Start",
    "Stop",
    "Swimlane",
    "Switch",
    "While",
    # Class
    "ClassDiagram",
    "ClassDiagramElement",
    "ClassNode",
    "ClassNote",
    "ClassType",
    "HideShow",
    "Member",
    "MemberModifier",
    "Package",
    "PackageStyle",
    "Relationship",
    "RelationType",
    "Separator",
    "SeparatorStyle",
    "Together",
    "Visibility",
    # Sequence
    "Activation",
    "ActivationAction",
    "Autonumber",
    "Box",
    "Delay",
    "Divider",
    "ElseBlock",
    "GroupBlock",
    "GroupType",
    "Message",
    "MessageArrowHead",
    "MessageLineStyle",
    "Participant",
    "ParticipantType",
    "Reference",
    "Return",
    "SequenceDiagram",
    "SequenceDiagramElement",
    "SequenceNote",
    "Space",
    # Component
    "Component",
    "ComponentDiagram",
    "ComponentElement",
    "ComponentNote",
    "ComponentRelationship",
    "ComponentRelationType",
    "ComponentStyle",
    "ComponentType",
    "Container",
    "ContainerType",
    "Interface",
    "Port",
    # Deployment
    "DeploymentDiagram",
    "DeploymentDiagramElement",
    "DeploymentElement",
    "DeploymentElementType",
    "DeploymentNote",
    "DeploymentRelationship",
    "DeploymentRelationType",
    # UseCase
    "Actor",
    "ActorStyle",
    "UseCase",
    "UseCaseContainer",
    "UseCaseContainerType",
    "UseCaseDiagram",
    "UseCaseDiagramElement",
    "UseCaseNote",
    "UseCaseRelationship",
    "UseCaseRelationType",
    # Object
    "Field",
    "Map",
    "MapEntry",
    "Object",
    "ObjectDiagram",
    "ObjectDiagramElement",
    "ObjectNote",
    "ObjectRelationship",
    "ObjectRelationType",
    # State
    "CompositeState",
    "ConcurrentState",
    "PseudoState",
    "PseudoStateKind",
    "Region",
    "StateDiagram",
    "StateDiagramElement",
    "StateNode",
    "Transition",
    # JSON/YAML
    "JsonDiagram",
    "YamlDiagram",
    # MindMap
    "MindMapDiagram",
    "MindMapDiagramStyle",
    "MindMapDiagramStyleLike",
    "MindMapNode",
]
